name: Entregables act1 y act 2

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Paso 1 - Checkout repo
        uses: actions/checkout@v4

      - name: Paso 2 - Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.2'

      - name: Paso 3 - Actualizar pip
        run: pip install --upgrade pip

      - name: Paso 4 - Instalar dependencias
        run: pip install -e .

      - name: Paso 5 - Ejecutar script principal
        run: python main.py

      - name: Paso 6 - Commit y Push de archivos generados
        uses: stefanzweifel/git-auto-commit-action@v5

    
        with:
          commit_message: |
             Datos actualizados: histórico, enriquecido, modelo y métricas generados automáticamente
          commit_user_name: Julio Muñoz [GitHub Actions]
          commit_user_email: julio.munozr@est.iudigital.edu.co
          commit_author: Julio Muñoz <julio.munozr@est.iudigital.edu.co>
          file_pattern: |
            src/static/data/historical.csv
            src/static/data/enriched_data.csv
            src/static/models/model.pkl
            src/static/models/metrics.csv
            logs/*.log
